app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::auth();

Route::resource('/students', 'StudentController'); // this will handle all /student routes, RESTfully

app/Student.php
<?php

namespace App;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;

class Student extends Model
{

    protected $fillable = ['first_name', 'second_name', 'third_name', 'email', 'birthday', 'school_entry', 'form'];

    protected $dates = ['birthday', 'school_entry'];

    public function getNameAttribute() {
        $names = array_only($this->attributes, ['first_name', 'second_name', 'third_name']);

        return implode(' ', $names);
    }

    public function getAgeAttribute() {
        return Carbon::now()->diffInYears($this->birthday);
    }

    public function getBirthdayClearAttribute() {
        return $this->birthday->format('d-m-Y');
    }

    public function getSchoolEntryClearAttribute() {
        return $this->school_entry->format('d-m-Y');
    }

    public function getFormAttribute($form_letter) {
        $now = Carbon::now();
        $form_year = $now->diffInYears($this->school_entry);

        if($now->month < 9) $form_year++;

        return $form_year . '-' . $form_letter;
    }

    public function setBirthdayAttribute($value) {
        $this->attributes['birthday'] = Carbon::createFromFormat('d-m-Y', $value);
    }

    public function setSchoolEntryAttribute($value) {
        $this->attributes['school_entry'] = Carbon::createFromFormat('d-m-Y', $value);
    }

}

app/User.php
<?php

namespace App;

use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesResources;

class Controller extends BaseController
{
    use AuthorizesRequests, AuthorizesResources, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/StudentController.php
<?php

namespace App\Http\Controllers;

use App\Student;
use Illuminate\Http\Request;

use App\Http\Requests;

class StudentController extends Controller
{
    /**
     * Create a new controller instance.
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $students = Student::all();

        return view('student.index', compact('students'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('student.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        Student::create($request->all());

        return back();
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param Student $student
     * @return \Illuminate\Http\Response
     * @internal param int $id
     */
    public function edit($id)
    {
        $student = Student::findOrFail($id);

        return view('student.edit', compact('student'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param Student                   $student
     * @return \Illuminate\Http\Response
     * @internal param int $id
     */
    public function update(Request $request, $id)
    {
        Student::findOrFail($id)->update($request->all());

        return back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param Student $student
     * @return \Illuminate\Http\Response
     * @internal param int $id
     */
    public function destroy($id)
    {
        Student::findOrFail($id)->delete();

        return back();
    }
}

resources/views/app.blade.php
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>База студентів</title>

        <link rel="stylesheet" href="{{ elixir('assets/css/app.css') }}">

        <style>
            .fa-btn {
                margin-right: 6px;
            }
        </style>
    </head>
    <body id="app-layout">

        <div id="sidebar-wrapper">
            @include('partials.sidebar')
        </div>

        <div id="wrapper">
            <div id="page-content-wrapper">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="panel panel-default">
                                <div class="panel-heading">@yield('heading')</div>
                                <div class="panel-body">
                                    @yield('content')
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        @include('partials.modals')

        <script src="{{ elixir('assets/js/app.js') }}"></script>
    </body>
</html>

resources/views/partials/modals.blade.php
<div class="modal fade" id="confirmDelete" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                Видалення запису #<span class="idConfirmDeleteId"></span>
            </div>
            <div class="modal-body">
                Ви впевнені, що хочете видалити запис про студента #<span class="idConfirmDeleteId"></span>?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Відмінити</button>
                <a class="btn btn-danger btn-ok" id="removeStudent" data-student-id="">Видалити</a>
            </div>
        </div>
    </div>
</div>

resources/views/partials/sidebar.blade.php
<ul class="sidebar-nav">
    <li class="sidebar-brand">
        <a href="/">
            База студентів
        </a>
    </li>
    @if(Auth::check())
        <li>
            <a href="{{ url('/students') }}">Список студентів</a>
        </li>
        <li>
            <a href="{{ url('/students/create') }}">Створити запис</a>
        </li>
        <li>
            Авторизовано як {{ Auth::user()->name }}
        </li>
        <li>
            <a href="{{ url('/logout') }}">Вийти</a>
        </li>
    @else
        <li><a href="{{ url('/login') }}">Авторизація</a></li>
        <li><a href="{{ url('/register') }}">Реєстрація</a></li>
    @endif
</ul>

resources/views/student/_form.blade.php
<form class="form-horizontal">
    <div class="form-group">
        <label for="inputFirstName" class="col-sm-1 control-label">Ім'я</label>
        <div class="col-sm-4">
            <input type="text" class="form-control" id="inputFirstName" placeholder="Ім'я" name="first_name" value="{{ $attrs['first_name'] or '' }}">
        </div>
    </div>
    <div class="form-group">
        <label for="inputSecondName" class="col-sm-1 control-label">Прізвище</label>
        <div class="col-sm-4">
            <input type="text" class="form-control" id="inputSecondName" placeholder="Прізвище" name="second_name" value="{{ $attrs['second_name'] or '' }}">
        </div>
    </div>
    <div class="form-group">
        <label for="inputThirdName" class="col-sm-1 control-label">По батькові</label>
        <div class="col-sm-4">
            <input type="text" class="form-control" id="inputThirdName" placeholder="По батькові" name="third_name" value="{{ $attrs['third_name'] or '' }}">
        </div>
    </div>
    <div class="form-group">
        <label for="inputEmail" class="col-sm-1 control-label">Email</label>
        <div class="col-sm-4">
            <input type="email" class="form-control" id="inputEmail" placeholder="Email" name="email" value="{{ $attrs['email'] or '' }}">
        </div>
    </div>
    <div class="form-group">
        <label for="inputBirthday" class="col-sm-1 control-label">Дата народження</label>
        <div class="col-sm-4">
            <div class="input-group date">
                <input class="form-control idDatePicker" id="inputBirthday" placeholder="" name="birthday" data-date="{{ $attrs['birthday'] or '' }}">
                <span class="input-group-addon">
                    <span class="glyphicon glyphicon-calendar"></span>
                </span>
            </div>
        </div>
    </div>
    <div class="form-group">
        <label for="inputSchoolEntry" class="col-sm-1 control-label">Дата вступу</label>
        <div class="col-sm-4">
            <div class="input-group date">
                <input class="form-control idDatePicker" id="inputSchoolEntry" placeholder="" name="school_entry" data-date="{{ $attrs['school_entry'] or \Carbon\Carbon::now()->format('Y-m-d') }}">
                <span class="input-group-addon">
                    <span class="glyphicon glyphicon-calendar"></span>
                </span>
            </div>
        </div>
    </div>
    <div class="form-group">
        <label for="inputForm" class="col-sm-1 control-label">Клас</label>
        <div class="col-sm-4">
            <select class="form-control" id="inputForm">
                <option {{ (array_key_exists('form', $attrs) && $attrs['form'] == 'А') ? 'selected' : '' }}>А</option>
                <option {{ (array_key_exists('form', $attrs) && $attrs['form'] == 'Б') ? 'selected' : '' }}>Б</option>
                <option {{ (array_key_exists('form', $attrs) && $attrs['form'] == 'В') ? 'selected' : '' }}>В</option>
                <option {{ (array_key_exists('form', $attrs) && $attrs['form'] == 'Г') ? 'selected' : '' }}>Г</option>
            </select>
        </div>
    </div>
    <div class="form-group">
        <div class="col-sm-offset-1 col-sm-10">
            <button type="submit" class="btn btn-success">Зберегти</button>
        </div>
    </div>
</form>

resources/views/student/create.blade.php
@extends('app')

@section('heading')
    Створення студента
@endsection

@section('content')
    <form class="form-horizontal" method="POST" action="/students">
        <input type="hidden" name="_method" value="POST">
        @include('student._form', ['attrs' => []])
    </form>
@endsection

resources/views/student/edit.blade.php
@extends('app')

@section('heading')
    Редагування студента #{{ $student->id }}
@endsection

@section('content')
    <form class="form-horizontal" method="POST" action="/students/{{ $student->id }}">
        <input type="hidden" name="_method" value="PUT">
        @include('student._form', ['attrs' => $student->getAttributes()])
    </form>
@endsection

resources/views/student/index.blade.php
@extends('app')

@section('heading')
    Список студентів
@endsection

@section('content')
    <table class="table table-bordered table-hover dt-bootstrap" id="students" cellspacing="0" width="100%" data-order='[[1, "asc"]]'>
        <thead>
            <tr>
                <th data-sortable="false">Дії</th>
                <th>Ім'я</th>
                <th>Прізвище</th>
                <th>По батькові</th>
                <th>Клас</th>
                <th>Вік</th>
                <th>Дата народження</th>
                <th>Дата вступу</th>
                <th>Email</th>
            </tr>
        </thead>
        <tbody>
            @forelse($students as $student)
                <tr>
                    <td data-student-id="{{ $student->id }}">
                        <button type="button" class="btn btn-xs btn-danger idDeleteStudent">
                            <span class="glyphicon glyphicon-trash"></span>&nbsp;
                        </button>
                        <button type="button" class="btn btn-xs btn-warning idEditStudent">
                            <span class="glyphicon glyphicon-edit"></span>&nbsp;
                        </button>
                    </td>
                    <td>{{ $student->first_name }}</td>
                    <td>{{ $student->second_name }}</td>
                    <td>{{ $student->third_name }}</td>
                    <td>{{ $student->form }}</td>
                    <td>{{ $student->age }}</td>
                    <td>{{ $student->birthday_clear }}</td>
                    <td>{{ $student->school_entry_clear }}</td>
                    <td>{{ $student->email }}</td>
                </tr>
            @empty
                <tr>
                    <td>-</td>
                    <td>-</td>
                    <td>-</td>
                    <td>-</td>
                    <td>-</td>
                    <td>-</td>
                    <td>-</td>
                    <td>-</td>
                    <td>-</td>
                </tr>
            @endforelse
        </tbody>
    </table>
@endsection